# Generated by Django 4.2.2 on 2023-07-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_generatedphoto_created_at_photo_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedphoto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
